### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by maniecodes** [JohannesMilke/local_push_notifications#2]
* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.lifecycle:lifecycle-runtime' has different version for the compile (2.0.0-rc01) and runtime (2.0.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
AndroidX incompatibilities may have caused this build to fail. Please migrate your app to AndroidX. See https://goo.gl/CP92wY.
Gradle task assembleDebug failed with exit code 1

**Comment by ademargomes** [comment]
Got the same just now. Did you manage to get any advice on this?

**Comment by maniecodes** [comment]
> Got the same just now. Did you manage to get any advice on this?

You can choose to migrate to AndroidX using Android Studio or you just create a new project "flutter create --androidx project-name"  then you copy and replace the lib folder of this project.

**Comment by ademargomes** [comment]
yeah, i went the other way and used the pub directly in my project. so all good for both.
cheers
